import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import BooksProvider from "@/contexts/booksContext";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100","200","300","400","500","600","700","800","900"],
});

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${poppins.variable} antialiased`}>
                    <BooksProvider>{children}</BooksProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
